version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=fts
      - POSTGRES_USER=fts
      - POSTGRES_PASSWORD=fts
      - PGDATA=/var/lib/postgresql-15/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata: